name: resto_radar
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <=4.0.0'

dependencies:
  android_alarm_manager_plus: ^3.0.4
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.3.2
  flutter_native_splash: ^2.3.5
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  http: ^1.2.0
  intl: ^0.19.0
  lottie: ^3.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.2.0
  provider: ^6.1.1
  readmore: ^2.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo/ic_restaurant.png'
  adaptive_icon_foreground: 'assets/logo/ic_launcher.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_food.png
    - assets/images/ic_juice.png
    - assets/images/search.png
    - assets/images/not-found.png
    - assets/images/empty-data.png
    - assets/images/no-internet.png
    - assets/lotties/loading.json
